import {
  TEAL,
  TEAL_SOFT,
  ROSE,
  ROSE_SOFT,
  INK,
  MIST,
  SILVER,
  FG_MUTED,
  FG_SUBTLE,
  LINE,
  FONT_DISPLAY,
  FONT_SANS,
  FONT_MONO,
} from "./theme";

const styles = {
  page: {
    minHeight: "100vh",
    background: MIST,
    color: INK,
    fontFamily: FONT_SANS,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    position: "relative",
  },
  progressTrack: {
    position: "sticky",
    top: 0,
    width: "100%",
    height: "3px",
    background: LINE,
    zIndex: 10,
  },
  progressFill: {
    height: "100%",
    background: TEAL,
    transition: "width 220ms cubic-bezier(0.22, 1, 0.36, 1)",
  },
  mainContent: {
    flex: "1 0 auto",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  logo: {
    width: "56px",
    height: "56px",
    marginTop: "48px",
    marginBottom: "24px",
  },
  eyebrow: {
    fontFamily: FONT_SANS,
    fontWeight: 500,
    fontSize: "12px",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: TEAL,
    marginBottom: "20px",
  },
  introWrap: {
    maxWidth: "560px",
    padding: "0 28px 80px",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  introTitle: {
    fontFamily: FONT_DISPLAY,
    fontWeight: 600,
    fontSize: "40px",
    lineHeight: 1.12,
    letterSpacing: "-0.025em",
    margin: "0 0 24px 0",
  },
  introBody: {
    fontFamily: FONT_SANS,
    fontSize: "18px",
    lineHeight: 1.65,
    color: FG_MUTED,
    marginBottom: "40px",
    maxWidth: "480px",
  },
  introFoot: {
    fontFamily: FONT_MONO,
    fontSize: "11px",
    color: FG_SUBTLE,
    marginTop: "16px",
    letterSpacing: "0.02em",
  },
  quizWrap: {
    maxWidth: "560px",
    width: "100%",
    padding: "56px 28px 80px",
    display: "flex",
    flexDirection: "column",
  },
  meta: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontFamily: FONT_MONO,
    fontSize: "11px",
    letterSpacing: "0.04em",
    color: FG_SUBTLE,
    marginBottom: "28px",
  },
  metaCategory: {
    color: TEAL,
    textTransform: "uppercase",
  },
  followUpTag: {
    display: "inline-block",
    fontFamily: FONT_MONO,
    fontSize: "10px",
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: ROSE,
    background: ROSE_SOFT,
    padding: "4px 10px",
    borderRadius: "999px",
    marginBottom: "16px",
    width: "fit-content",
  },
  questionText: {
    fontFamily: FONT_DISPLAY,
    fontWeight: 600,
    fontSize: "26px",
    lineHeight: 1.3,
    letterSpacing: "-0.01em",
    margin: "0 0 36px 0",
  },
  confidenceSub: {
    fontFamily: FONT_SANS,
    fontSize: "15px",
    lineHeight: 1.5,
    color: FG_MUTED,
    marginTop: "-24px",
    marginBottom: "32px",
  },
  optionsList: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    marginBottom: "40px",
  },
option: {
    textAlign: "left",
    fontFamily: FONT_SANS,
    fontSize: "16px",
    lineHeight: 1.5,
    color: INK,
    border: `1px solid ${LINE}`,
    borderRadius: "10px",
    padding: "16px 18px",
    cursor: "pointer",
    boxShadow: "0 1px 2px rgba(32,32,32,0.06)",
    transition: "border-color 140ms cubic-bezier(0.22, 1, 0.36, 1), background 140ms cubic-bezier(0.22, 1, 0.36, 1), box-shadow 140ms cubic-bezier(0.22, 1, 0.36, 1)",
  },
  optionSelected: {
    border: `1px solid ${TEAL}`,
    background: TEAL_SOFT,
    boxShadow: "0 2px 6px rgba(32,32,32,0.07), 0 1px 2px rgba(32,32,32,0.04)",
  },
  primaryBtn: {
    fontFamily: FONT_SANS,
    fontWeight: 500,
    fontSize: "15px",
    color: "#FFFFFF",
    background: TEAL,
    border: "none",
    borderRadius: "10px",
    height: "52px",
    padding: "0 28px",
    boxSizing: "border-box",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    letterSpacing: "0.01em",
    transition: "background 140ms cubic-bezier(0.22, 1, 0.36, 1), opacity 140ms cubic-bezier(0.22, 1, 0.36, 1)",
  },
  navRow: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  backBtn: {
    fontFamily: FONT_SANS,
    fontWeight: 500,
    fontSize: "14px",
    color: FG_MUTED,
    background: "transparent",
    border: "none",
    height: "52px",
    padding: "0 4px",
    boxSizing: "border-box",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  secondaryBtn: {
    fontFamily: FONT_SANS,
    fontWeight: 500,
    fontSize: "14px",
    color: INK,
    background: "transparent",
    border: `1px solid ${SILVER}`,
    borderRadius: "10px",
    height: "52px",
    padding: "0 24px",
    boxSizing: "border-box",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  shareRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "12px",
  },
  secondaryBtnLink: {
    fontFamily: FONT_SANS,
    fontWeight: 500,
    fontSize: "14px",
    color: INK,
    background: "transparent",
    border: `1px solid ${SILVER}`,
    borderRadius: "10px",
    height: "52px",
    padding: "0 24px",
    boxSizing: "border-box",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    textDecoration: "none",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(32,32,32,0.55)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "20px",
    zIndex: 1000,
  },
  modalCard: {
    position: "relative",
    background: MIST,
    borderRadius: "14px",
    maxWidth: "420px",
    width: "100%",
    maxHeight: "90vh",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    boxShadow: "0 20px 50px rgba(32,32,32,0.25)",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "flex-end",
    flexShrink: 0,
    padding: "10px 10px 0",
  },
  modalBody: {
    overflowY: "auto",
    minHeight: 0,
    flex: "1 1 auto",
    padding: "0 24px 28px",
  },
  modalClose: {
    background: "transparent",
    border: "none",
    fontSize: "26px",
    lineHeight: 1,
    color: FG_SUBTLE,
    cursor: "pointer",
    padding: "6px 8px",
  },
  confirmCard: {
    position: "relative",
    background: MIST,
    borderRadius: "14px",
    padding: "32px 28px 28px",
    maxWidth: "360px",
    width: "100%",
    maxHeight: "90vh",
    overflowY: "auto",
    boxShadow: "0 20px 50px rgba(32,32,32,0.25)",
  },
  confirmTitle: {
    fontFamily: FONT_DISPLAY,
    fontWeight: 700,
    fontSize: "22px",
    color: INK,
    margin: "0 0 12px 0",
  },
  confirmBody: {
    fontFamily: FONT_SANS,
    fontSize: "15px",
    lineHeight: 1.6,
    color: FG_MUTED,
    margin: "0 0 28px 0",
  },
  confirmBtnRow: {
    display: "flex",
    gap: "12px",
    flexWrap: "wrap",
  },
  modalDividerLabel: {
    textAlign: "center",
    fontFamily: FONT_MONO,
    fontSize: "11px",
    color: FG_SUBTLE,
    letterSpacing: "0.03em",
    margin: "18px 0",
  },
  previewCard: {
    background: "#FFFFFF",
    border: `1px solid ${LINE}`,
    borderRadius: "12px",
    padding: "28px 20px",
    textAlign: "center",
    marginBottom: "24px",
  },
  previewLogo: {
    width: "40px",
    height: "40px",
    marginBottom: "12px",
  },
  previewEyebrow: {
    fontFamily: FONT_SANS,
    fontWeight: 600,
    fontSize: "11px",
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: TEAL,
    marginBottom: "10px",
  },
  previewArchetype: {
    fontFamily: FONT_DISPLAY,
    fontWeight: 700,
    fontSize: "26px",
    color: INK,
    marginBottom: "22px",
    letterSpacing: "-0.02em",
  },
  previewStatsRow: {
    display: "flex",
    justifyContent: "center",
    gap: "24px",
    marginBottom: "22px",
  },
  previewStatItem: {
    textAlign: "center",
  },
  previewStatLabel: {
    fontFamily: FONT_MONO,
    fontSize: "9px",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: FG_SUBTLE,
    marginBottom: "4px",
  },
  previewStatValue: {
    fontFamily: FONT_DISPLAY,
    fontWeight: 700,
    fontSize: "22px",
    color: INK,
  },
  previewDivider: {
    borderTop: `1px solid ${LINE}`,
    paddingTop: "16px",
  },
  previewTagline: {
    fontFamily: FONT_SANS,
    fontSize: "12px",
    color: FG_MUTED,
    marginBottom: "4px",
  },
  previewLink: {
    fontFamily: FONT_SANS,
    fontWeight: 600,
    fontSize: "13px",
    color: TEAL,
  },
  btnRow: {
    marginTop: "48px",
    display: "flex",
    flexWrap: "wrap",
    gap: "12px",
  },
  shareLine: {
    fontFamily: FONT_MONO,
    fontSize: "12px",
    color: FG_SUBTLE,
    marginTop: "20px",
    letterSpacing: "0.01em",
  },
  footer: {
    width: "100%",
    maxWidth: "560px",
    padding: "32px 28px 40px",
    textAlign: "center",
    borderTop: `1px solid ${LINE}`,
    marginTop: "16px",
    flexShrink: 0,
  },
  footerDisclaimer: {
    fontFamily: FONT_SANS,
    fontSize: "12px",
    lineHeight: 1.5,
    color: FG_SUBTLE,
    margin: "0 0 8px 0",
  },
  footerCopyright: {
    fontFamily: FONT_MONO,
    fontSize: "11px",
    color: FG_SUBTLE,
    margin: 0,
    letterSpacing: "0.02em",
  },
  resultsWrap: {
    maxWidth: "600px",
    width: "100%",
    padding: "48px 28px 100px",
    display: "flex",
    flexDirection: "column",
  },
  tierName: {
    fontFamily: FONT_DISPLAY,
    fontWeight: 700,
    fontSize: "34px",
    letterSpacing: "-0.02em",
    color: INK,
    marginBottom: "14px",
  },
  newcomerBadge: {
    display: "inline-block",
    fontFamily: FONT_MONO,
    fontSize: "11px",
    letterSpacing: "0.03em",
    color: ROSE,
    background: ROSE_SOFT,
    padding: "6px 12px",
    borderRadius: "999px",
    marginBottom: "20px",
    width: "fit-content",
  },
  tierSummary: {
    fontFamily: FONT_SANS,
    fontSize: "18px",
    lineHeight: 1.65,
    color: FG_MUTED,
    marginBottom: "8px",
    maxWidth: "540px",
  },
  triangleOuter: {
    width: "100%",
    maxWidth: "340px",
    margin: "28px auto 8px",
  },
  triangleCaptionTop: {
    textAlign: "center",
    fontFamily: FONT_MONO,
    fontSize: "10px",
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: FG_SUBTLE,
    marginBottom: "6px",
  },
  triangleCaptionRow: {
    display: "flex",
    justifyContent: "space-between",
    fontFamily: FONT_MONO,
    fontSize: "10px",
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: FG_SUBTLE,
    marginTop: "8px",
  },
  triangleSquare: {
    position: "relative",
    width: "100%",
    aspectRatio: "1 / 0.92",
  },
  triangleShape: {
    position: "absolute",
    inset: 0,
    background: "#FFFFFF",
    border: `1px solid ${LINE}`,
    boxShadow: "0 1px 2px rgba(32,32,32,0.06)",
    clipPath: "polygon(50% 2%, 2% 98%, 98% 98%)",
  },
  trianglePartitions: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    pointerEvents: "none",
  },
  triangleDot: {
    position: "absolute",
    width: "16px",
    height: "16px",
    borderRadius: "50%",
    background: TEAL,
    border: "2px solid #FFFFFF",
    boxShadow: `0 0 0 1px ${TEAL}, 0 4px 10px rgba(29,126,139,0.35)`,
    transform: "translate(-50%, -50%)",
  },
  scorePairRow: {
    display: "flex",
    gap: "24px",
    marginTop: "20px",
    marginBottom: "32px",
    justifyContent: "center",
  },
  scorePairItem: {
    textAlign: "center",
  },
  scorePairLabel: {
    fontFamily: FONT_MONO,
    fontSize: "10px",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: FG_SUBTLE,
    marginBottom: "4px",
  },
  scorePairValue: {
    fontFamily: FONT_DISPLAY,
    fontWeight: 700,
    fontSize: "24px",
    color: INK,
  },
  sectionLabel: {
    fontFamily: FONT_MONO,
    fontSize: "11px",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: FG_SUBTLE,
    marginBottom: "12px",
  },
  insightBlock: {
    marginBottom: "28px",
    paddingTop: "24px",
    borderTop: `1px solid ${LINE}`,
  },
  insightText: {
    fontFamily: FONT_SANS,
    fontSize: "16px",
    lineHeight: 1.6,
    color: FG_MUTED,
    margin: 0,
    maxWidth: "540px",
  },
  recBlock: {
    paddingTop: "8px",
  },
  recList: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  recItem: {
    fontFamily: FONT_SANS,
    fontSize: "16px",
    lineHeight: 1.6,
    color: FG_MUTED,
    paddingLeft: "20px",
    position: "relative",
    borderLeft: `2px solid ${ROSE}`,
    background: ROSE_SOFT,
    paddingTop: "12px",
    paddingBottom: "12px",
    paddingRight: "16px",
    borderRadius: "0 10px 10px 0",
  },
};
export default styles;
